# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-inspector
  description: Terraform module to provision AWS Inspector
  homepage: https://cloudposse.com/accelerate
  topics: compliance, terraform, hcl2, terraform-modules, aws
